name: Matrix Test

on:
  workflow_dispatch:

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Export matrix.json
        id: set-matrix
        run: |
          echo ::set-output name=matrix::$(cat gh-matrix.json)

  build:
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}

    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest

    steps:
      - name: Log
        run: |
          echo ${{ matrix }}
