name: Steam Manual Release

on:
  workflow_dispatch:

jobs:
  deployToSteam:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.1

      - name: Download executables
        run: npm run steam

      - uses: game-ci/steam-deploy@v1
        with:
          appId: ${{ secrets.STEAM_APP_ID }}
          username: ${{ secrets.STEAM_USERNAME }}
          password: ${{ secrets.STEAM_PASSWORD }}
          configVdf: ${{ secrets.STEAM_CONFIG_VDF}}
          ssfnFileName: ${{ secrets.STEAM_SSFN_FILE_NAME }}
          ssfnFileContents: ${{ secrets.STEAM_SSFN_FILE_CONTENTS }}
          buildDescription: v0.0.1
          rootPath: steam # see bin/steam.js
          depot1Path: osx # see bin/steam.js
          releaseBranch: github
